In [6]:
import pandas as pd
df=pd.read_csv("/content/archive.zip")

This cell imports the `pandas` library, which is essential for data manipulation and analysis in Python. It then reads a CSV file named `archive.zip` (which is likely a compressed CSV or contains a CSV within it) into a pandas DataFrame named `df`. This DataFrame will hold the entire dataset for subsequent operations.

In [7]:
df

,Index,Title,Artist,Top Genre,Year,Beats Per Minute (BPM),Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity
0,1,Sunrise,Norah Jones,adult standards,2004,157,30,53,-14,11,68,201,94,3,71
1,2,Black Night,Deep Purple,album rock,2000,135,79,50,-11,17,81,207,17,7,39
2,3,Clint Eastwood,Gorillaz,alternative hip hop,2001,168,69,66,-9,7,52,341,2,17,69
3,4,The Pretender,Foo Fighters,alternative metal,2007,173,96,43,-4,3,37,269,0,4,76
4,5,Waitin' On A Sunny Day,Bruce Springsteen,classic rock,2002,106,82,58,-5,10,87,256,1,3,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989,1990,Heartbreak Hotel,Elvis Presley,adult standards,1958,94,21,70,-12,11,72,128,84,7,63
1990,1991,Hound Dog,Elvis Presley,adult standards,1958,175,76,36,-8,76,95,136,73,6,69
1991,1992,Johnny B. Goode,Chuck Berry,blues rock,1959,168,80,53,-9,31,97,162,74,7,74
1992,1993,Take Five,The Dave Brubeck Quartet,bebop,1959,174,26,45,-13,7,60,324,54,4,65
1993,1994,Blueberry Hill,Fats Domino,adult standards,1959,133,50,49,-10,16,83,148,74,3,56

This cell simply displays the entire DataFrame `df`. This is a quick way to inspect the loaded data, including its columns, rows, and general structure, helping to confirm that the data was loaded correctly.

In [8]:
df.isnull().sum()

Index                     0
Title                     0
Artist                    0
Top Genre                 0
Year                      0
Beats Per Minute (BPM)    0
Energy                    0
Danceability              0
Loudness (dB)             0
Liveness                  0
Valence                   0
Length (Duration)         0
Acousticness              0
Speechiness               0
Popularity                0
dtype: int64

This cell checks for missing values in each column of the DataFrame `df`. `df.isnull()` returns a boolean DataFrame indicating `True` for missing values and `False` otherwise. `.sum()` then counts the number of `True` values (missing values) for each column. The output shows that there are no missing values in any of the columns.

In [9]:
df.duplicated().sum()

np.int64(0)

This cell checks for duplicate rows in the DataFrame `df`. `df.duplicated()` returns a boolean Series indicating `True` for rows that are duplicates of previous rows. `.sum()` then counts the number of `True` values. The output `np.int64(0)` indicates that there are no duplicate rows in the dataset.

In [10]:
df.describe()

,Index,Year,Beats Per Minute (BPM),Energy,Danceability,Loudness (dB),Liveness,Valence,Acousticness,Speechiness,Popularity
count,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.00000
mean,997.500000,1992.992979,120.215647,59.679539,53.238215,-9.008526,19.012036,49.408726,28.858074,4.994985,59.52658
std,575.762538,16.116048,28.028096,22.154322,15.351507,3.647876,16.727378,24.858212,29.011986,4.401566,14.35160
min,1.000000,1956.000000,37.000000,3.000000,10.000000,-27.000000,2.000000,3.000000,0.000000,2.000000,11.00000
25%,499.250000,1979.000000,99.000000,42.000000,43.000000,-11.000000,9.000000,29.000000,3.000000,3.000000,49.25000
50%,997.500000,1993.000000,119.000000,61.000000,53.000000,-8.000000,12.000000,47.000000,18.000000,4.000000,62.00000
75%,1495.750000,2007.000000,136.000000,78.000000,64.000000,-6.000000,23.000000,69.750000,50.000000,5.000000,71.00000
max,1994.000000,2019.000000,206.000000,100.000000,96.000000,-2.000000,99.000000,99.000000,99.000000,55.000000,100.00000

This cell generates descriptive statistics for the numerical columns in the DataFrame `df`. It provides insights into the central tendency, dispersion, and shape of the distribution of each column, such as count, mean, standard deviation, minimum, maximum, and interquartile ranges. This helps in understanding the spread and potential outliers in the data.

In [11]:
df=df.drop("Index",axis=1)

This cell drops the 'Index' column from the DataFrame `df`. The `axis=1` argument specifies that a column should be dropped. This is a common step in data preprocessing when an index column is redundant or not needed for analysis, as pandas DataFrames already have their own implicit index.

This cell prepares data for clustering and performs K-Means clustering. It first selects a subset of numerical features into a new DataFrame `df2`. It then attempts to initialize `MinMaxScaler` for each column, but this part of the code is incomplete as the `MinMaxScaler` object is created but not used to actually scale the data. It then initializes and runs `KMeans` clustering with `n_clusters=10` on `df2`. Finally, it calculates and prints the Silhouette Score, which is a metric used to evaluate the quality of clusters. A higher Silhouette Score indicates better-defined clusters.

In [13]:
df["Music Segments"] = clusters
MinMaxScaler(df["Music Segments"])
df["Music Segments"] = df["Music Segments"].map({1: "Cluster 1", 2:
    "Cluster 2", 3: "Cluster 3", 4: "Cluster 4", 5: "Cluster 5",
    6: "Cluster 6", 7: "Cluster 7", 8: "Cluster 8",
    9: "Cluster 9", 10: "Cluster 10"})

This cell assigns the `clusters` generated by the K-Means algorithm to a new column named `"Music Segments"` in the original DataFrame `df`. It then attempts to scale the `"Music Segments"` column, but similar to the previous cell, `MinMaxScaler` is initialized but not applied. After that, it maps the numerical cluster labels (e.g., 0, 1, 2...) to more descriptive string labels (e.g., "Cluster 1", "Cluster 2"...) for better readability and interpretation.

In [14]:
df.head()

,Title,Artist,Top Genre,Year,Beats Per Minute (BPM),Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity,Music Segments
0,Sunrise,Norah Jones,adult standards,2004,157,30,53,-14,11,68,201,94,3,71,Cluster 5
1,Black Night,Deep Purple,album rock,2000,135,79,50,-11,17,81,207,17,7,39,Cluster 1
2,Clint Eastwood,Gorillaz,alternative hip hop,2001,168,69,66,-9,7,52,341,2,17,69,Cluster 3
3,The Pretender,Foo Fighters,alternative metal,2007,173,96,43,-4,3,37,269,0,4,76,Cluster 3
4,Waitin' On A Sunny Day,Bruce Springsteen,classic rock,2002,106,82,58,-5,10,87,256,1,3,59,Cluster 6

This cell displays the first 5 rows of the modified DataFrame `df` using `df.head()`. This allows for a quick check to see the newly added `"Music Segments"` column and how the cluster labels have been assigned and mapped.

In [15]:
import plotly.graph_objects as go
PLOT = go.Figure()
for i in list(df["Music Segments"].unique()):


    PLOT.add_trace(go.Scatter3d(x = df[df["Music Segments"]== i]['Beats Per Minute (BPM)'],
                                y = df[df["Music Segments"] == i]['Energy'],
                                z = df[df["Music Segments"] == i]['Danceability'],
                                mode = 'markers',marker_size = 6, marker_line_width = 1,
                                name = str(i)))
PLOT.update_traces(hovertemplate='Beats Per Minute (BPM): %{x} <br>Energy: %{y} <br>Danceability: %{z}')


PLOT.update_layout(width = 800, height = 800, autosize = True, showlegend = True,
                   scene = dict(xaxis=dict(title = 'Beats Per Minute (BPM)', titlefont_color = 'black'),
                                yaxis=dict(title = 'Energy', titlefont_color = 'black'),
                                zaxis=dict(title = 'Danceability', titlefont_color = 'black')),
                   font = dict(family = "Gilroy", color  = 'black', size = 12))

This cell generates an interactive 3D scatter plot using `plotly.graph_objects`. It iterates through each unique 'Music Segment' (cluster) and plots the 'Beats Per Minute (BPM)', 'Energy', and 'Danceability' for songs belonging to that cluster. Each cluster is represented by a different color. The plot is configured with custom axis labels, title, and hover information for better visualization and exploration of the clusters in a 3D space.

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import MinMaxScaler # Import MinMaxScaler

# Define df2 with the relevant features for clustering
df2 = df[["Beats Per Minute (BPM)", "Loudness (dB)",
              "Liveness", "Valence", "Acousticness",
              "Speechiness"]]

# Scale df2 to create df2_scaled
scaler = MinMaxScaler()
df2_scaled = scaler.fit_transform(df2)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(df2_scaled, clusters, test_size=0.2, random_state=42)

# Classifier train karein
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

# Predictions aur Accuracy
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("--- Supervised Classification Accuracy ---")
print(f"Cluster Prediction Accuracy: {acc * 100:.2f}%")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

--- Supervised Classification Accuracy ---
Cluster Prediction Accuracy: 95.49%

Classification Report:
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        36
           1       0.89      0.89      0.89        36
           2       0.98      0.91      0.94        44
           3       0.98      0.95      0.96        43
           4       0.94      0.97      0.95        31
           5       1.00      0.86      0.92        14
           6       0.96      1.00      0.98        70
           7       0.97      0.98      0.98        64
           8       1.00      0.84      0.91        19
           9       0.95      0.98      0.96        42

    accuracy                           0.95       399
   macro avg       0.96      0.94      0.95       399
weighted avg       0.96      0.95      0.95       399

This cell performs supervised classification using a RandomForestClassifier to predict the music segments. It first splits the data into training and testing sets using `train_test_split`. Note that `df2_scaled` is used here, but it was not explicitly scaled in previous cells, which might lead to unexpected results if `df2` was not scaled prior to this step. It then trains a `RandomForestClassifier` on the training data (`X_train`, `y_train`). After training, it makes predictions on the test set (`X_test`) and calculates the `accuracy_score`. Finally, it prints the classification accuracy and a detailed `classification_report`, which includes precision, recall, and f1-score for each cluster, providing a comprehensive evaluation of the model's performance.

In [18]:
import joblib

# =========================
# SAVE MODEL
# =========================
joblib.dump(clf, "cluster_random_forest.pkl")

print("Model dumped successfully!")


# =========================
# LOAD MODEL
# =========================
loaded_model = joblib.load("cluster_random_forest.pkl")

print("Model loaded successfully!")


# =========================
# PREDICTION
# =========================
y_pred = loaded_model.predict(X_test)

acc = accuracy_score(y_test, y_pred)

print("--- Loaded Model Accuracy ---")
print(f"Cluster Prediction Accuracy: {acc * 100:.2f}%")

print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

Model dumped successfully!
Model loaded successfully!
--- Loaded Model Accuracy ---
Cluster Prediction Accuracy: 95.49%

Classification Report:
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        36
           1       0.89      0.89      0.89        36
           2       0.98      0.91      0.94        44
           3       0.98      0.95      0.96        43
           4       0.94      0.97      0.95        31
           5       1.00      0.86      0.92        14
           6       0.96      1.00      0.98        70
           7       0.97      0.98      0.98        64
           8       1.00      0.84      0.91        19
           9       0.95      0.98      0.96        42

    accuracy                           0.95       399
   macro avg       0.96      0.94      0.95       399
weighted avg       0.96      0.95      0.95       399

This cell focuses on saving, loading, and evaluating the trained `RandomForestClassifier` model using the `joblib` library. First, it saves the `clf` (classifier) object to a file named `cluster_random_forest.pkl` using `joblib.dump()`. This process is called serialization. Then, it loads the saved model from the `.pkl` file back into a new variable `loaded_model` using `joblib.load()`, which is deserialization. Finally, it uses the `loaded_model` to make predictions on the `X_test` dataset and evaluates its performance by calculating the `accuracy_score` and printing a `classification_report`, confirming that the loaded model performs identically to the original trained model.

In [19]:
from sklearn.preprocessing import MinMaxScaler
for i in df.columns:
    MinMaxScaler(i)
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=10)
clusters = kmeans.fit_predict(df2)
score = silhouette_score(df2, clusters)
print(f"Silhouette Score: {score:.4f}")

Silhouette Score: 0.2383